name: Twister
description: Run twister and upload the report
inputs:
  args:
    description: 'The arguments to pass to twister'
    required: false
    default: ''
  path:
    description: 'The path where to fetch the sources'
    required: true
  name:
    description: 'The name, used to for reporting'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - uses: ./esphome/.github/actions/zephyr-setup
      with:
        path: ${{ inputs.path }}
        name: "(All)"

    - name: Build firmware
      shell: bash
      run: |
        west twister -T ${{ inputs.path }}/app -v --inline-logs ${{ inputs.args }}

    - name: Publish Unit Test Results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        check_name: Unit Test Results ${{ inputs.name }}
        files: "**/twister.xml"
        comment_mode: off
