/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: api_options.proto */

#ifndef PROTOBUF_C_api_5foptions_2eproto__INCLUDED
#define PROTOBUF_C_api_5foptions_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/descriptor.pb-c.h"

typedef struct Void Void;

/* --- enums --- */

typedef enum _APISourceType {
	APISOURCE_TYPE__SOURCE_BOTH = 0,
	APISOURCE_TYPE__SOURCE_SERVER = 1,
	APISOURCE_TYPE__SOURCE_CLIENT = 2 PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(APISOURCE_TYPE)
} APISourceType;

/* --- messages --- */

struct Void {
	ProtobufCMessage base;
};
#define VOID__INIT {PROTOBUF_C_MESSAGE_INIT(&void__descriptor)}

/* Void methods */
void void__init(Void *message);
size_t void__get_packed_size(const Void *message);
size_t void__pack(const Void *message, uint8_t *out);
size_t void__pack_to_buffer(const Void *message, ProtobufCBuffer *buffer);
Void *void__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data);
void void__free_unpacked(Void *message, ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Void_Closure)(const Void *message, void *closure_data);

/* --- services --- */

/* --- descriptors --- */

extern const ProtobufCEnumDescriptor apisource_type__descriptor;
extern const ProtobufCMessageDescriptor void__descriptor;

PROTOBUF_C__END_DECLS

#endif /* PROTOBUF_C_api_5foptions_2eproto__INCLUDED */
