/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: api_options.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "api_options.pb-c.h"
void void__init(Void *message)
{
	static const Void init_value = VOID__INIT;
	*message = init_value;
}
size_t void__get_packed_size(const Void *message)
{
	assert(message->base.descriptor == &void__descriptor);
	return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t void__pack(const Void *message, uint8_t *out)
{
	assert(message->base.descriptor == &void__descriptor);
	return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t void__pack_to_buffer(const Void *message, ProtobufCBuffer *buffer)
{
	assert(message->base.descriptor == &void__descriptor);
	return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Void *void__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
{
	return (Void *)protobuf_c_message_unpack(&void__descriptor, allocator, len, data);
}
void void__free_unpacked(Void *message, ProtobufCAllocator *allocator)
{
	if (!message) {
		return;
	}
	assert(message->base.descriptor == &void__descriptor);
	protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
#define void__field_descriptors     NULL
#define void__field_indices_by_name NULL
#define void__number_ranges         NULL
const ProtobufCMessageDescriptor void__descriptor = {
	PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
	"void",
	"Void",
	"Void",
	"",
	sizeof(Void),
	0,
	void__field_descriptors,
	void__field_indices_by_name,
	0,
	void__number_ranges,
	(ProtobufCMessageInit)void__init,
	NULL,
	NULL,
	NULL /* reserved[123] */
};
static const ProtobufCEnumValue apisource_type__enum_values_by_number[3] = {
	{"SOURCE_BOTH", "APISOURCE_TYPE__SOURCE_BOTH", 0},
	{"SOURCE_SERVER", "APISOURCE_TYPE__SOURCE_SERVER", 1},
	{"SOURCE_CLIENT", "APISOURCE_TYPE__SOURCE_CLIENT", 2},
};
static const ProtobufCIntRange apisource_type__value_ranges[] = {{0, 0}, {0, 3}};
static const ProtobufCEnumValueIndex apisource_type__enum_values_by_name[3] = {
	{"SOURCE_BOTH", 0},
	{"SOURCE_CLIENT", 2},
	{"SOURCE_SERVER", 1},
};
const ProtobufCEnumDescriptor apisource_type__descriptor = {
	PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
	"APISourceType",
	"APISourceType",
	"APISourceType",
	"",
	3,
	apisource_type__enum_values_by_number,
	3,
	apisource_type__enum_values_by_name,
	1,
	apisource_type__value_ranges,
	NULL,
	NULL,
	NULL,
	NULL /* reserved[1234] */
};
