# Copyright (c) 2024 Alexandre Bailon
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: anobli
      url-base: https://github.com/anobli/

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import: true
    - name: protobuf-c
      revision: a41892bb04cbd9fad18e32953c3fb1498f93ce70
      path: modules/lib/protobuf-c
      remote: anobli
