# A YAML binding matching the node

compatible: "nabucasa,wifi-credentials"
description: "Wifi credentials DTS backend"

include: [base.yaml]

child-binding:
  properties:
    reg:
      type: int
    ssid:
      type: string
      description: wifi SSID of wifi access point to connect to
      required: true
    password:
      type: string
      description: wifi password
      required: true
    security:
      type: string
      description: wifi security type
      enum:
        - "none"
        - "psk"
        - "wep"
        - "wpa-psk"
        - "wpa-auto-personal"
      default: "psk"
    timeout:
      type: int
      description: Timeout for connecting to the network
      default: 0
