# A YAML binding matching the node

compatible: "nabucasa,esphome-switch-gpio"
description: "Enable support of esphome gpio switch"

include: [base.yaml, "nabucasa,esphome-entity.yaml"]

properties:
    gpios:
      type: phandle-array
      required: true
    restore_mode:
      type: string
      enum:
        - "SWITCH_ALWAYS_OFF"
        - "SWITCH_ALWAYS_ON"
        - "SWITCH_RESTORE_DEFAULT_OFF"
        - "SWITCH_RESTORE_DEFAULT_ON"
        - "SWITCH_RESTORE_INVERTED_DEFAULT_OFF"
        - "SWITCH_RESTORE_INVERTED_DEFAULT_ON"
        - "SWITCH_RESTORE_DISABLED"
      required: false
      default: "SWITCH_ALWAYS_OFF"
